# Generated by Django 2.0.1 on 2018-04-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='email',
            field=models.EmailField(help_text='required for contact form', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='sections',
            field=models.ManyToManyField(help_text='at least 1 section is required', to='siteinfo.Section', verbose_name='Sections'),
        ),
    ]
