# Generated by Django 2.0.1 on 2018-04-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0003_auto_20180425_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Section Name')),
            ],
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='sections',
            field=models.ManyToManyField(help_text='at least 1 section is required', to='siteinfo.Section', verbose_name='Sections'),
        ),
    ]
