# Generated by Django 2.0.1 on 2018-05-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0004_auto_20180425_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='section',
            name='label_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Section Name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(editable=False, max_length=50, verbose_name='ID Name'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='articles_files/', verbose_name='Logo'),
        ),
    ]
