# Generated by Django 2.0.1 on 2018-03-06 14:32

import articles
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', articles.MultiSelectField(choices=[('slider-home', '[Home/Slider] (1377*700)')], max_length=1000, verbose_name='Block')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Link')),
                ('file', models.FileField(blank=True, help_text='Image or flash file.', null=True, upload_to='articles_files/', verbose_name='File')),
                ('file_caption', models.TextField(blank=True, null=True, verbose_name='File Caption')),
                ('video', models.CharField(blank=True, max_length=400, null=True, verbose_name='Video')),
                ('is_public', models.BooleanField(default=True, verbose_name='Is Public?')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Publication Date')),
                ('pub_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Publication End Date')),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='Creation Date')),
            ],
        ),
    ]
