# Generated by Django 2.0.1 on 2018-04-17 12:42

import apps.main
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='block',
            field=apps.main.MultiSelectField(choices=[('slider-home', '[Home/Slider] (1377*700)'), ('service-home', '[Home/Service] (icon 88*58)')], max_length=1000, verbose_name='Block'),
        ),
    ]
