# Generated by Django 2.0.1 on 2018-05-03 14:33

import apps.main
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180417_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='block',
            field=apps.main.MultiSelectField(choices=[('slider-home', '[Home/Slider] (1377*700)'), ('service-home', '[Home/Service] (icon 88*58)'), ('fun-facts', '[Home/FunFacts]'), ('portfolio', '[Home/Portfolio] (project image)')], max_length=1000, verbose_name='Block'),
        ),
    ]
